# https://karlley.hatenablog.jp/entry/2022/09/08/192419
# https://zenn.dev/junara/articles/efa04ce1ab02c9
exclude:
  - '**/vendor/**/*'
  - '**/node_modules/**/*'
glob: "**/*.{html,text,js}{+*,}.erb"
linters:
  Rubocop:
    enabled: true
    rubocop_config:
      inherit_from:
        - .rubocop.yml
      Layout/InitialIndentation:
        Enabled: false
      Layout/TrailingEmptyLines:
        Enabled: false
      Style/FrozenStringLiteralComment:
        Enabled: false
  SelfClosingTag:
    enabled: false
