inherit_from: .rubocop_todo.yml

require:
  - rubocop-ast
  - rubocop-rspec
  - rubocop-rails
  - rubocop-performance

AllCops:
  Exclude:
    - "config.ru"
    - "bin/**"
    - "lib/**"
    - "db/schema.rb"
    - "db/**/*"
    - "config/**/*"
    - "node_modules/**/*"
    - "script/**/*"
    - !ruby/regexp /old_and_unused\.rb$/
    - "vendor/**/*"
    - "Gemfile.lock"
  NewCops: enable
  StyleGuideBaseURL: https://github.com/fortissimo1997/ruby-style-guide/blob/japanese/README.ja.md
  TargetRubyVersion: 2.7.7

Layout/EmptyLines:
  Exclude:
    - "Gemfile"
    - "bin/setup"

Layout/EmptyLinesAroundBlockBody:
  Exclude:
    - "db/schema.rb"

Layout/LineLength:
  Max: 250

Layout/SpaceInsideArrayLiteralBrackets:
  Exclude:
    - "config/environments/production.rb"

# TODO: 動作確認後に削除する
# Lint/UnusedMethodArgument:
#   Enabled: false

# 開発者が感じていたプログラムの 匂い を定量的に判断する
# Offense count: 2
# default 15
Metrics/AbcSize:
  Max: 29

Metrics/BlockLength:
  Exclude:
    - "lib/tasks/seed_fu_gen.rake"

Metrics/BlockNesting:
  Max: 5

Metrics/CyclomaticComplexity:
  Exclude:
    - "app/helpers/keywords_helper.rb"

Metrics/MethodLength:
  Enabled: false

Rails/FilePath:
  Enabled: false

Rails/I18nLocaleTexts:
  Enabled: false

#  capybara固有のメソッドを有効にする
RSpec/Capybara:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

# TODO: あとでDefault valueを決める
# https://docs.rubocop.org/rubocop-rspec/cops_rspec.html#rspecexamplelength
RSpec/ExampleLength:
  Enabled: false
  # Max: 5 (default)

RSpec/InstanceVariable:
  Enabled: false
  # Exclude:
  #   - spec/requests/*.rb
  #   - spec/requests/*/*.rb

RSpec/LetSetup:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/ReturnFromStub:
  EnforcedStyle: block

# 日本語でのコメントを許可
Style/AsciiComments:
  Enabled: false

# モジュール名::クラス名の定義を許可
Style/ClassAndModuleChildren:
  Enabled: false

# クラスにコメントを残さない
Style/Documentation:
  Enabled: false

# 文字リテラルのイミュータブル宣言を無視（freezeになるのはRuby3以降）

Style/HashLikeCase:
  Exclude:
    - "app/helpers/keywords_helper.rb"

Style/MixinUsage:
  Exclude:
    - "bin/setup"
    - "bin/update"

Style/PercentLiteralDelimiters:
  Exclude:
    - "config/spring.rb"

Style/RedundantSelf:
  Enabled: false
