version: "3.7"

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: root
    ports:
      - "4306:3306"
    volumes:
      - db-data:/var/lib/mysql
  web:
    init: true
    tty: true
    stdin_open: true
    build: .
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/webapp
      - bundle:/usr/local/bundle:cached
      - node-modules:/webapp/node_modules:cached
      - yarn-cache:/usr/local/share/.cache/yarn/v6:cached
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      RAILS_ENV: development
      MYSQL_HOST: db
  # https://qiita.com/undrthemt/items/52a557cb937d133b7140
  # https://blog.furu07yu.com/entry/build-docker-rails-webpacker#:~:text=8%20--locale%3DC%22-,webpacker,-%3A%0A%20%20%20%20%23%20Dockerfile%E3%82%92%E4%BD%BF
  # https://qiita.com/wancoro/items/9175a6fdcbab17840d2a#webpacker%E3%81%AE%E8%B5%B7%E5%8B%95
  webpacker:
    build: .
    # command: bash -c 'rm -rf public/packs/* || true && bin/webpack-dev-server'
    command: 'bin/webpack-dev-server'
    environment:
      RAILS_ENV: development
      WEBPACKER_DEV_SERVER_HOST: 0.0.0.0
    ports:
      - "3035:3035"
    stdin_open: true
    tty: true
    volumes:
      - .:/webapp
      - bundle:/usr/local/bundle:cached
    depends_on:
      - web

volumes:
  bundle:
    driver: local
  db-data:
    driver: local
  node-modules:
    driver: local
  # public-data:
  #   driver: local
  # tmp-data:
  #   driver: local
  yarn-cache:
    driver: local
