FROM ruby:2.7.7

ENV APP_DIR /webapp
ENV APT_KEY_DONT_WARN_ON_DANGEROUS_USAGE yes
ENV DEBCONF_NOWARNINGS yes
ENV JOBS_NUMBER 4
ENV LANG C.UTF-8
ENV MY_BUNDLER_VERSION 2.4.6
ENV RAILS_ENV production
ENV RAILS_SERVE_STATIC_FILES=1
WORKDIR /webapp

RUN curl -fsSL https://deb.nodesource.com/setup_14.x | bash - \
  && curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - \
  && echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list \
  && apt-get update -qq \
  && apt-get install -y --no-install-recommends \
  build-essential \
  libpq-dev \
  vim \
  nodejs\
  yarn

COPY Gemfile Gemfile.lock /webapp/
COPY package.json yarn.lock /webapp/
RUN gem install bundler --no-document -v ${MY_BUNDLER_VERSION} \
  && bundle config set without development test \
  && bundle install -j${JOBS_NUMBER} \
  && yarn install --production --frozen-lockfile \
  && yarn cache clean
COPY . /webapp

COPY entrypoint.sh /usr/bin/
RUN chmod +x /usr/bin//entrypoint.sh
ENTRYPOINT [ "entrypoint.sh" ]

CMD ["rails", "server", "-b", "0.0.0.0", "-p", "${PORT:-3000}"]
