$(function () {


  function extractRawmaterialFromDB(rawmaterial_form_value) {
    // console.log("3:" + rawmaterial_form_value)
    // DBから rawmaterial.name, rawmaterial.unit.nameを取得したい
    // もしできるなら一括で取得したい
    // extract rawmaterial_name
    let unit_id;
    $.ajax({
      type: 'GET',
      url: '/managers/foodstuffs/extract_rawmaterial_name',
      data: { rawmaterial_id_param: rawmaterial_form_value },
      datatype: 'json'
    }).done(function (data) {
      console.log(data)
      // insert data to badge
      $("#rawmaterial_name").html(data.name)
      console.log("unit_id:" + data.unit_id)
      // 上記のajaxで取得した data.unit_id から
      // rawmaterial.unit.nameを取得
      // #rawmaterial_measure_unitに単位を挿入したい
      // extract rawmaterial_measure_unit
      $.ajax({
        type: 'GET',
        url: '/managers/foodstuffs/extract_rawmaterial_measure_unit',
        data: { unit_id_param: data.unit_id },
        datatype: 'json'
      }).done(function (data) {
        console.log(data)
        // $("#rawmaterial_measure_unit").html(data.name)
        d.resolve();
      })
    })
  }

  let action_name = $('body').data('action')
  // console.log(action_name);

  const csrfToken = document.querySelector('[name="csrf-token"]').getAttribute('content');

  let h_value_rawmaterial_id


  switch (action_name) {
    //   case "index":
    //     break;
    //   case "show":
    //     break;
    case "new":
    case "create":
      // check existence of cuisine_id
      // saveメソッドが失敗した時に実行してほしい
      h_value_rawmaterial_id = $('#foodstuff_rawmaterial_id').val()
      console.log(h_value_rawmaterial_id)

      if (h_value_rawmaterial_id) {
        $('#choiced_rawmaterial').show()
        // extract rawmaterial info from db
        extractRawmaterialFromDB(h_value_rawmaterial_id)
        $(".search_rawmaterial").hide()
      } else {
        $('#choiced_rawmaterial').hide()
      }

      // increamental search
      let preFunc = null;
      preInput = '';
      input = '';

      ajaxSearch = function () {
        $.ajax({
          type: 'GET',
          url: '/managers/foodstuffs/search_rawmaterial',
          data: { keyword: input },
          datatype: 'json'
        })
      }

      // search rawmaterial
      $("#search_rawmaterial").on("keyup", function () {
        input = $.trim($("#search_rawmaterial").val());
        if (preInput !== input) {
          clearTimeout(preFunc);
          setTimeout(ajaxSearch, 1000);
          console.log(input);
        }
        preInput = input;
        $('#search_results').show()
      })

      // get clicked-element(choice rawmaterial)
      $(document).on('click', 'div.rawmaterial', function () {
        // console.log(this)
        // console.log(this.dataset.unitName)
        // rawmaterial_idを取得
        let clicked_rawmaterial_id = parseInt((this.id).replace("rawmaterial_", ""))
        // rawmaterial_idを代入
        // console.log(this.textContent)
        $('#foodstuff_rawmaterial_id').val(clicked_rawmaterial_id)
        // 食材名をバッジt内に表示
        $('#rawmaterial_name').text(this.textContent)
        // バッジを表示
        $('#choiced_rawmaterial').show()
        // 数量フォームに単位を表示する
        $('.input-group-text').text(this.dataset.unitName)
        // 検索フォームを非表示にする
        $("#search_rawmaterial").hide()
        // 検索結果を非表示
        $('#search_results').hide()
        $('.rawmaterial').hide()
      })

      // reset choiced rawmaterial
      $("#btnResetRawmaterial").on("click", function () {
        // alert内の原材料名をクリアする
        $('#rawmaterial_name').text("")
        // 原材料idの値をクリアする
        $('#foodstuff_rawmaterial_id').val("")
        // 検索フォームをクリアする
        $('#search_rawmaterial').val("")
        // 数量フォームの単位をクリア
        $('.input-group-text').text("")
        // 検索フォームを表示する
        $('.search_rawmaterial').show()
        $('#search_rawmaterial').show()
        // 非表示する
        $('#choiced_rawmaterial').hide()
      })
      break;
    default:
      //     console.log("not passed");
      break;
  }
});

// $(document).ready(function () {
//   return $("#new_article").on("ajax:success", function (event) {
//     var data, ref, status, xhr;
//     ref = event.detail, data = ref[0], status = ref[1], xhr = ref[2];
//     return $("#new_article").append(xhr.responseText);
//   }).on("ajax:error", function (event) {
//     return $("#new_article").append("<p>ERROR</p>");
//   });
// });

// ---
// generated by coffee-script 1.9.2
