default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: password
  host: db
  pool: 5
  timeout: 5000

production:
  <<: *default
  database: <%= ENV['HEROKU_DB_DATABASE_NAME'] %>
  encoding: utf8
  host: <%= ENV['HEROKU_DB_HOST'] %>
  username: <%= ENV['HEROKU_DB_USERNAME'] %>
  password: <%= ENV['HEROKU_DB_PASSWORD'] %>
  url: <%= ENV['JAWSDB_URL'] %>
