import 'jquery/dist/jquery'
import Rails from 'rails-ujs/lib/assets/compiled/rails-ujs'
import 'popper.js/dist/umd/popper'
import 'bootstrap/dist/js/bootstrap'
import 'admin-lte/dist/js/adminlte'
import 'admin-lte/dist/js/demo'
